### ISSUE TITLE
dropdown sub menu?

### ISSUE THREAD

**Issue by oscdoctest** [chromatical/jekyll-materialdocs#1]
Is there a way to get dropdown sub menu in the navigation bar? Basically the sub menu appears only when we click on any of the main menus...

**Comment by chromatical** [comment]
Currently no, though it is a good idea and shouldn't be difficult to make `_includes/menu.html` work that way.  I'll add it to my todo list and see if I can get to it soon.  If you are familiar with Jekyll theming, you can always fork, edit, and submit a PR.

**Comment by chromatical** [comment]
@oscdoctest I've just pushed out a new version with this feature.  Put `menu_style: dropdown` in `_config.yml` to enable it.

**Comment by oscdoctest** [comment]
Thats great!! Thanks..
