### ISSUE TITLE
External links in menu?

### ISSUE THREAD

**Issue by tspike** [chromatical/jekyll-materialdocs#2]
Loving this theme- it's exactly what I was looking for. I'm wondering if it's possible to add an external link to the menu?

**Comment by chromatical** [comment]
Not currently, but I'm open to the idea.  A `menu.yml` data file would do the trick, and shouldn't be difficult to implement.  I'll put it on my todo list and see if I can get to it soon.

**Comment by chromatical** [comment]
@tspike I've just pushed out a new release that adds support for data-driven menus in `_data/nav.yml`.  There is an example `nav.yml` in the README.  Let me now if you find any bugs!  :bug: :bug:

**Comment by tspike** [comment]
Kickass! Thanks so much
