### ISSUE TITLE
Search button not working

### ISSUE THREAD

**Issue by ericklau** [chromatical/jekyll-materialdocs#3]
Hi I was using your jekyll theme on my github for some documentation however my search button is not linking properly.  For example when I click the search button icon it the webpage takes me to https://pages.github.boozallencsn.com/demo/search instead of https://pages.github.boozallencsn.com/Lau-Erickson/demo/search which is the correct url.  

below is my config.yaml!  Let me know if you could possible help me with this issue because I really like your template but the search button is a problem for me!

# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: MaterialDocs
email: hello@chromaticaldesign.com
description: A demo site for the Jekyll MaterialDocs theme.
baseurl: "/demo" # the subpath of your site, e.g. /blog
url: "https://pages.github.boozallencsn.com/Lau-Erickson" # the base hostname & protocol for your site, e.g. http://example.com
menu_style: dropdown
highlight: rouge
copyright:
# Build settings
markdown: kramdown
plugins:
  - jekyll-remote-theme
remote_theme: chromatical/jekyll-materialdocs
exclude:
  - Gemfile
  - Gemfile.lock

**Comment by chromatical** [comment]
Changing `url` to `https://pages.github.boozallencsn.com` and `baseurl` to `/Lau-Erickson/demo` should fix the problem.  Could you try that and let me know if it works?

**Comment by ericklau** [comment]
Hi thank you for the response I tried switching my config to that and when I click the search button i get a link to https://pages.github.boozallencsn.com/Lau-Erickson/demo/Lau-Erickson/demo/search.  Which is also not the right pathing.  Is there anything else I could try?  Thanks in advance I appreciate your help!

**Comment by chromatical** [comment]
Can you double-check that the `url` parameter is set to `https://pages.github.boozallencsn.com`?

**Comment by chromatical** [comment]
Your `baseurl` parameter needs a prepended `/`, so:
`baseurl: "/Lau-Erickson/demo"`
I think that should fix your problem.

**Comment by ericklau** [comment]
got it thank you so much @chromatical 👍the search started pathing correctly I really appreciate your help!
